### ISSUE TITLE
Keyboard power issue

### ISSUE THREAD

**Issue by zeke7237** [TheByteAttic/CERBERUS2100#14]
I have an Agon2light, and recently received my Cerebrus 2100. I fought with keyboard issues for a few weeks, none of the keyboards that worked with Agon would work with Cerebrus. No powerup sequence on the keyboard lights. 
I ordered another keyboard (from Agon Australia) just to be sure, and it didn't work either!
I was looking around at it again this morning, and discovered that if I plugged in the keyboard AFTER powering up the Cerebrus the blinkenlights appeared and the keyboard works!
I'm going to attempt to look at the firmware..

**Comment by TheByteAttic** [comment]
This is not normal. CERBERUS 2100 should have the keyboard connected before power up. All keyboards that work with Agon should work with CERBERUS.

**Comment by TheByteAttic** [comment]
Please let me know if you found out what the problem was.

**Comment by zeke7237** [comment]
Unfortunately I'm in the middle of moving, so I won't have my tools and
test equipment available for a while. I'll report back when I can.
